import os
import json
import requests

from dotenv import load_dotenv

load_dotenv()

MCP_URL = os.getenv("SNOWFLAKE_MCP_URL")
SNOWFLAKE_PAT = os.getenv("SNOWFLAKE_PAT")

if not MCP_URL:
    raise ValueError("Missing SNOWFLAKE_MCP_URL in .env")

if not SNOWFLAKE_PAT:
    raise ValueError("Missing SNOWFLAKE_PAT in .env")


class MCPToolError(RuntimeError):
    """Raised when an MCP tool reports an application-level error."""


def parse_mcp_response(response: requests.Response) -> dict:
    if response.status_code != 200:
        raise RuntimeError(
            f"MCP call failed. Status={response.status_code}, Body={response.text}"
        )

    try:
        payload = response.json()
    except requests.exceptions.JSONDecodeError as exc:
        raise RuntimeError(
            f"MCP endpoint returned invalid JSON. Body={response.text}"
        ) from exc

    result = payload.get("result", {})
    if result.get("isError"):
        messages = [
            item.get("text", "")
            for item in result.get("content", [])
            if item.get("type") == "text"
        ]
        detail = "\n".join(filter(None, messages)) or json.dumps(payload)
        raise MCPToolError(detail)

    if "error" in payload:
        raise MCPToolError(json.dumps(payload["error"]))

    return payload


def call_mcp_tool(tool_name: str, arguments: dict) -> dict:
    """
    Calls a Snowflake-managed MCP tool using JSON-RPC.
    """
    payload = {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "tools/call",
        "params": {
            "name": tool_name,
            "arguments": arguments
        }
    }

    headers = {
        "Authorization": f"Bearer {SNOWFLAKE_PAT}",
        "Content-Type": "application/json"
    }

    response = requests.post(
        MCP_URL,
        headers=headers,
        json=payload,
        timeout=120
    )

    return parse_mcp_response(response)


def ask_tpch(question: str) -> dict:
    """
    Ask a natural language question against TPCH_SF10 using Cortex Analyst.
    """
    return call_mcp_tool(
        tool_name="tpch_analyst",
        arguments={
            "message": question
        }
    )



def extract_sql_from_analyst_response(response: dict) -> str:
    """
    Extracts generated SQL statement from the Cortex Analyst MCP response.
    """
    content = response.get("result", {}).get("content", [])

    if not content:
        raise ValueError("No content found in MCP response.")

    text_payload = content[0].get("text")

    if not text_payload:
        raise ValueError("No text payload found in MCP response.")

    analyst_items = json.loads(text_payload)

    for item in analyst_items:
        if "statement" in item:
            return item["statement"]

    raise ValueError("No SQL statement found in analyst response.")

def clean_generated_sql(sql: str) -> str:
    """
    Removes Cortex Analyst comments and trailing semicolon.
    """
    lines = []

    for line in sql.splitlines():
        if "Generated by Cortex Analyst" in line:
            continue
        lines.append(line)

    cleaned = "\n".join(lines).strip()

    if cleaned.endswith(";"):
        cleaned = cleaned[:-1].strip()

    return cleaned

def execute_sql(sql: str) -> dict:
    return call_mcp_tool(
        tool_name="tpch_sql_exec",
        arguments={
            "sql": sql.strip()
        }
    )

def list_tools() -> dict:
    """
    Lists tools exposed by the Snowflake MCP server.
    This helps us confirm the exact input argument names.
    """
    payload = {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "tools/list"
    }

    headers = {
        "Authorization": f"Bearer {SNOWFLAKE_PAT}",
        "Content-Type": "application/json"
    }

    response = requests.post(
        MCP_URL,
        headers=headers,
        json=payload,
        timeout=120
    )

    return parse_mcp_response(response)



if __name__ == "__main__":
    

    sql_result = execute_sql("SELECT 1 AS TEST_VALUE")
    print(json.dumps(sql_result, indent=2))
